### ISSUE TITLE
Uncaught exception when loading project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#81]
When loading or creating a project that uses the Flip board type, the following message appears in the console. This appears to happen only in the Chrome browser.

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

```
{id: 50, name: "test", description: "test", description-html: "<p>test</p>↵", type: "PROPC", …}
board: "flip"
code: "<xml xmlns="http://www.w3.org/1999/xhtml"></xml>"
created: "2018/12/13 21:10"
description: "test"
description-html: "<p>test</p>↵"
id: 50
modified: "2018/12/13 21:10"
name: "test"
private: true
shared: false
type: "PROPC"
user: "demo"
yours: true
__proto__: Object
```

**Comment by zfi** [comment]
I agree that it doesn't appear to be causing any UI issues. What I don't understand is why the play is requested in the first place. Are we using animated GIFs or some other think that requires it?

**Comment by MatzElectronics** [comment]
It's the sound effects when you connect or throw away blocks.

And in a new level of stupid - it's within the blockly core...and, we can't just redefine the function because it's defined and then immediately used - so the only way to fix it is to edit the core itself (tested - it does work):

replace:
`b.play();b.pause();`

with:
`b.load();`

**Comment by zfi** [comment]
This issue is resolved. Closing.
